# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Social Coding Diary
email: mail@christianpoplawski.de
description: > # this means to ignore newlines until "baseurl:"
  Diese Jekyll-Seite ist mein Tagebuch für das WPF Social Coding.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://plsr.github.io/social-coding-diary" # the base hostname & protocol for your site
twitter_username: _chrispop
github_username: plsr

# Build settings
markdown: kramdown
